'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { ArrowUpRight,ArrowRight,Activity as ActivityIcon,Wallet,RefreshCw,Check,LoaderCircle,AlertCircle } from 'lucide-react';
import type { AppConfig,SwapRecord } from '../lib/types';
import { api,units,short,track } from '../lib/client';
import { useWallet } from './wallet';
import { AssetIcon } from './asset-picker';
export function Activity({config}:{config:AppConfig}){
 const wallet=useWallet();const [swaps,setSwaps]=useState<SwapRecord[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false),[refresh,setRefresh]=useState(0);
 useEffect(()=>{if(!wallet.address||!config.storageReady)return;const controller=new AbortController();setLoading(true);api<{swaps:SwapRecord[]}>(`/v1/swaps?wallet=${wallet.address}`,undefined,controller.signal).then(r=>{setSwaps(r.swaps);setError('');}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>setLoading(false));return()=>controller.abort();},[wallet.address,config.storageReady,refresh]);
 return <section className="content-page activity-page"><div className="page-eyebrow">EVERY MOVE, ON THE RECORD</div><div className="activity-heading"><h1>Your activity<span>.</span></h1><button className="secondary-button" aria-label="Refresh activity" onClick={()=>setRefresh(x=>x+1)}><RefreshCw size={16}/></button></div><p className="page-intro">Your swaps. Their routes. Every detail.</p>{error&&<p role="alert" className="error-box">{error}</p>}{loading?<div className="empty-state"><LoaderCircle className="spin" size={26}/><p>Loading your activity…</p></div>:swaps.length?<div className="activity-list">{swaps.map(s=><Link href={`/swap/${s.publicId}`} key={s.id}><div className="overlap-icons"><AssetIcon small asset={s.quote.sourceAsset}/><AssetIcon small asset={s.quote.destinationAsset}/></div><div><strong>{s.quote.sourceAsset.symbol} <ArrowRight size={14}/> {s.quote.destinationAsset.symbol}</strong><small>{units(s.route.amountInRaw,s.quote.sourceAsset.decimals)} {s.quote.sourceAsset.symbol}</small></div><div><span className={`status-tag ${s.status.toLowerCase()}`}>{s.status.replaceAll('_',' ')}</span><small>{new Date(s.createdAt).toLocaleString()}</small></div><ArrowUpRight size={17}/></Link>)}</div>:<div className="empty-state"><span className="empty-icon"><ActivityIcon size={30}/></span><h2>{wallet.address?'Your next move starts here.':'Your wallet tells the story.'}</h2><p>{wallet.address?'Your confirmed swaps and pending transactions will appear here.':'Connect your wallet to see your swap history and receipts.'}</p>{wallet.address?<Link className="primary-button inline-button" href="/">Make a swap <ArrowRight size={16}/></Link>:<button className="primary-button inline-button" onClick={wallet.open}><Wallet size={16}/>Connect wallet</button>}</div>}</section>;
}
export function Receipt({id,config}:{id:string;config:AppConfig}){
 const [swap,setSwap]=useState<SwapRecord|null>(null),[error,setError]=useState('');
 useEffect(()=>{let active=true;let timer:ReturnType<typeof setTimeout>;
 async function load(){try{const s=await api<SwapRecord>(`/v1/swaps/${id}`);if(!active)return;setSwap(s);setError('');if(s.status==='COMPLETED'){track('swap_completed');}else if(s.status!=='FAILED')timer=setTimeout(load,4000);}catch(e){if(active){setError(e instanceof Error?e.message:'Receipt unavailable.');timer=setTimeout(load,10000);}}}void load();
 try{const pending=JSON.parse(localStorage.getItem('stockswap:lastSubmission')||'null');if(pending?.swap_id===id)void api('/v1/swaps/submit',pending).catch(()=>{});}catch{}
 return()=>{active=false;clearTimeout(timer);};},[id]);
 const complete=swap?.status==='COMPLETED',failed=swap?.status==='FAILED';
 return <section className="receipt-page"><Link className="back-link" href="/activity">← Your activity</Link><div className="receipt-card"><span className={`receipt-icon ${complete?'complete':failed?'failed':''}`}>{complete?<Check size={30}/>:failed?<AlertCircle size={30}/>:<LoaderCircle className="spin" size={30}/>}</span><div className="page-eyebrow">STOCKSWAP RECEIPT</div><h1>{complete?'Swap complete':failed?'Swap unsuccessful':'Confirming your swap'}</h1><p className="page-intro">{complete?'Your output has been verified onchain.':failed?swap?.failureReason:'We’ll verify the transaction and token transfers before marking it complete.'}</p>{error&&<p className="error-box" role="alert">{error}</p>}{swap&&<><div className="receipt-amount"><AssetIcon asset={swap.quote.sourceAsset}/><div><small>You paid</small><strong>{units(swap.route.amountInRaw,swap.quote.sourceAsset.decimals)} {swap.quote.sourceAsset.symbol}</strong></div></div><div className="receipt-arrow"><ArrowRight size={20}/></div><div className="receipt-amount"><AssetIcon asset={swap.quote.destinationAsset}/><div><small>{complete?'You received':'Minimum output'}</small><strong className={complete?'green':''}>{units(complete?swap.actualOutRaw!:swap.route.minimumAmountOutRaw,swap.quote.destinationAsset.decimals)} {swap.quote.destinationAsset.symbol}</strong></div></div><dl className="detail-list"><div><dt>Status</dt><dd>{swap.status.replaceAll('_',' ')}</dd></div><div><dt>Route</dt><dd>{swap.quote.sourceAsset.symbol} → {swap.route.steps.length>1?'USDG → ':''}{swap.quote.destinationAsset.symbol}</dd></div><div><dt>Venue</dt><dd>{swap.route.provider}</dd></div><div><dt>Price impact at quote</dt><dd>{swap.route.priceImpactBps/100}%</dd></div><div><dt>Pool fees</dt><dd>{swap.route.steps.map(s=>s.feePips/10000+'%').join(' + ')}</dd></div><div><dt>Network fee</dt><dd>{units(swap.gasFeeWei||undefined,18,8)} ETH</dd></div><div><dt>Block</dt><dd>{swap.blockNumber||'Pending'}</dd></div><div><dt>Wallet</dt><dd>{short(swap.wallet)}</dd></div><div><dt>Network</dt><dd>{config.chainName}</dd></div></dl>{swap.txHash&&<a className="primary-button" href={`${config.explorerUrl}/tx/${swap.txHash}`} target="_blank" rel="noreferrer">View transaction <ArrowUpRight size={17}/></a>}<p className="fine-print">{complete?'Verified after 20 L2 confirmations. Ethereum settlement may take longer.':'This receipt keeps updating even if you close the swap page.'}</p><Link className="text-link" href="/">Make another swap <ArrowRight size={14}/></Link></>}</div></section>;
}
