'use client';
import { useState } from 'react';
import { Search,Check,ArrowUpRight } from 'lucide-react';
import type { SupportedAsset } from '../lib/types';
import { Modal } from './modal';
export function AssetIcon({asset,small=false}:{asset:SupportedAsset;small?:boolean}){return <span className={`asset-icon asset-${asset.symbol.toLowerCase()} ${small?'small':''}`}>{asset.symbol==='NVDA'?<svg viewBox="0 0 32 32" aria-hidden="true"><path d="M4 16c5-9 19-10 25 0-5 9-20 10-25 0Zm7 0a6 6 0 1 0 12 0 6 6 0 0 0-12 0Z" fill="none" stroke="currentColor" strokeWidth="2.5"/><circle cx="17" cy="16" r="2.8" fill="currentColor"/></svg>:asset.symbol==='AAPL'?<svg viewBox="0 0 32 32" aria-hidden="true"><path fill="currentColor" d="M20 7c1-2 1-4 1-5-3 1-5 3-5 6 2 0 3 0 4-1ZM26 21c-1 3-3 7-5 7-2 0-3-1-5-1s-3 1-5 1c-3-1-6-7-6-12 0-4 3-7 6-7 2 0 4 1 5 1s4-1 6-1c2 0 4 1 5 3-4 2-4 7-1 9Z"/></svg>:asset.symbol==='TSLA'?'T':asset.symbol==='META'?'∞':asset.symbol==='GOOGL'?'G':asset.symbol==='AMZN'?'a':asset.symbol==='MSFT'?'⊞':asset.symbol.slice(0,2)}</span>;}
export function AssetPicker({assets,selected,onSelect,onClose,testnet}:{assets:SupportedAsset[];selected?:string;onSelect:(asset:SupportedAsset)=>void;onClose:()=>void;testnet:boolean}){
 const [query,setQuery]=useState('');const found=assets.filter(a=>`${a.symbol} ${a.displayName}`.toLowerCase().includes(query.toLowerCase()));
 return <Modal title="Choose an asset" onClose={onClose}><div className="search-field"><Search size={19}/><input aria-label="Search assets" placeholder="Search ticker or company" value={query} onChange={e=>setQuery(e.target.value)} autoFocus/></div><div className="picker-label">VERIFIED ASSET CATALOG <span>{assets.length} assets</span></div>{testnet&&<p className="picker-notice">These verified assets are on mainnet. Testnet swaps are unavailable.</p>}<div className="asset-results">{found.map(a=><button className="asset-result" key={a.id} onClick={()=>{onSelect(a);onClose();}}><AssetIcon asset={a}/><span><strong>{a.symbol} <small>Stock Token</small></strong><span>{a.displayName}</span></span><span className="result-right">{a.id===selected?<Check size={18}/>:<small>Robinhood Chain</small>}</span></button>)}{!found.length&&<div className="search-empty"><Search size={28}/><h3>No verified asset found</h3><p>{query.toUpperCase()==='HOOD'?'HOOD is not in the canonical issuer registry.':'Try a company name or another ticker.'}</p></div>}</div><a href="https://docs.robinhood.com/chain/stock-tokens/" className="picker-disclosure" target="_blank" rel="noreferrer">What does a Stock Token represent? <ArrowUpRight size={14}/></a></Modal>;
}
